<a href="https://colab.research.google.com/github/M4r1nh0/classifica-o-binaria-com-pytorch-com-deep-learning---breast-cancer--02-/blob/master/projeto4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install 'torch==1.4.0'
!pip install 'skorch==0.7.0'

     |████████████████████████████████| 753.4MB 18kB/s 
ERROR: torchvision 0.7.0+cu101 has requirement torch==1.6.0, but you'll have torch 1.4.0 which is incompatible.
  Found existing installation: torch 1.6.0+cu101
    Uninstalling torch-1.6.0+cu101:
      Successfully uninstalled torch-1.6.0+cu101
     |████████████████████████████████| 112kB 2.6MB/s 


In [ ]:
import skorch
import torch

In [ ]:
torch.__version__
#skorch.__version__

'1.4.0'

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
import torch.nn as nn 
from sklearn.metrics import accuracy_score, confusion_matrix



In [ ]:
np.random.seed(123)
torch.manual_seed(123)

In [ ]:
previsores = pd.read_csv('entradas_breast.csv')
classe = pd.read_csv('saidas_breast.csv')

In [ ]:
previsores = torch.tensor(np.array(previsores),dtype=torch.float)
classe = torch.tensor(np.array(classe), dtype=torch.float)

In [ ]:
type(previsores)

torch.Tensor

In [ ]:
train_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(previsores, classe),batch_size=10, shuffle=True)

In [ ]:
class classificador_torch(nn.Module):
  def __init__(self):
    super().__init__()
    self.dense0 = nn.Linear(30, 8)
    torch.nn.init.normal_(self.dense0.weight, mean=0.0, std=0.5)
    self.dense1 = nn.Linear(8, 8)
    torch.nn.init.normal_(self.dense1.weight, mean=0.0, std=0.5)
    self.dense2 = nn.Linear(8, 1)
    self.activation = nn.ReLU()
    self.dropout = nn.Dropout(0.2)
    self.output = nn.Sigmoid()

  def forward(self, X):
    X = self.dense0(X)
    X = self.activation(X)
    X = self.dropout(X)
    X = self.dense1(X)
    X = self.activation(X)
    X = self.dropout(X)
    X = self.dense2(X)
    X = self.output(X)
    return X


In [ ]:
classificador = classificador_torch()

In [ ]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(classificador.parameters(), lr= 0.001, weight_decay=0.0001)

In [ ]:
for epoch in range(100):
  running_loss = 0.

  for data in train_loader:
    inputs, labels = data
    optimizer.zero_grad()
    
    outputs = classificador(inputs)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()

    running_loss += loss.item()

  print("epoca %3d:  perda %.5f"% (epoch+1,running_loss/len(train_loader)))

epoca   1:  perda 13.38004
epoca   2:  perda 12.50338
epoca   3:  perda 12.59775
epoca   4:  perda 12.79300
epoca   5:  perda 13.24940
epoca   6:  perda 13.06327
epoca   7:  perda 12.39310
epoca   8:  perda 11.71273
epoca   9:  perda 12.21542
epoca  10:  perda 12.32327
epoca  11:  perda 11.94399
epoca  12:  perda 11.58765
epoca  13:  perda 11.29416
epoca  14:  perda 11.47558
epoca  15:  perda 12.03560
epoca  16:  perda 11.46815
epoca  17:  perda 9.98088
epoca  18:  perda 10.97482
epoca  19:  perda 10.89189
epoca  20:  perda 10.95137
epoca  21:  perda 11.19680
epoca  22:  perda 10.99099
epoca  23:  perda 10.52222
epoca  24:  perda 11.11779
epoca  25:  perda 10.68309
epoca  26:  perda 11.43517
epoca  27:  perda 9.84482
epoca  28:  perda 10.93606
epoca  29:  perda 10.85919
epoca  30:  perda 10.18115
epoca  31:  perda 10.44960
epoca  32:  perda 10.24107
epoca  33:  perda 10.43825
epoca  34:  perda 10.36000
epoca  35:  perda 10.53449
epoca  36:  perda 10.40131
epoca  37:  perda 10.71957
epo

In [ ]:
novo = torch.tensor([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178,
                  0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015,
                  0.03, 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185,
                  0.84, 158, 0.363]], dtype=torch.float)

In [ ]:
classificador.eval()

classificador_torch(
  (dense0): Linear(in_features=30, out_features=8, bias=True)
  (dense1): Linear(in_features=8, out_features=8, bias=True)
  (dense2): Linear(in_features=8, out_features=1, bias=True)
  (activation): ReLU()
  (dropout): Dropout(p=0.2, inplace=False)
  (output): Sigmoid()
)

In [ ]:
previsão = classificador(novo)

In [ ]:
previsão = previsão.detach()

In [ ]:
previsão

tensor([[1.]])

In [ ]:
previsão = previsão.numpy()

In [ ]:
previsão

array([[1.]], dtype=float32)

In [ ]:
previsão = (previsão > 0.5)

In [ ]:
previsão

array([[ True]])

In [ ]:
classificador.state_dict()

OrderedDict([('dense0.weight',
              tensor([[-9.5399e-01,  5.0276e-01,  7.9644e-01,  3.0661e-01,  5.7747e-01,
                       -2.1210e-01,  1.0039e-01,  4.5799e-01, -6.1248e-01,  5.3102e-01,
                       -2.6070e-01, -9.7058e-02,  8.8793e-01, -9.0941e-02, -7.4881e-05,
                       -1.1193e-01, -5.5757e-04, -3.4775e-05, -1.4898e-02, -1.0758e-07,
                       -6.2589e-01, -2.3588e-01, -1.6525e-02,  7.3659e-01, -7.3633e-01,
                        6.1362e-01,  5.5634e-01,  1.8103e-01,  6.2705e-01,  4.9417e-01],
                      [ 5.2209e-01,  3.0962e-01,  9.1058e-01, -1.1141e-02,  7.4908e-03,
                        2.5305e-03,  2.2596e-01, -5.9632e-01, -3.5600e-01, -1.0434e-02,
                        5.1165e-01,  2.2529e-01, -8.4551e-01,  3.9808e-01, -2.3326e-07,
                        3.1248e-02,  7.9267e-04,  6.1902e-06,  3.2254e-02, -6.6710e-08,
                       -8.3435e-01,  6.1840e-01, -1.4277e-01, -8.3648e-02, -1.1169e+00,


In [ ]:
torch.save(classificador.state_dict(), 'checkpoint.pth')